#!/usr/bin/env python
import os
import sys

argv=sys.argv
names=[]

for idx in range(len(argv)):
 fl=argv[idx]
 if fl[-4:]==".pcp":
  name=fl[:-4]
  temp=name
  while not os.path.exists(temp):
   temp="_"+temp
  names+=[temp]
  argv[idx]="%s.c"%name
  os.system("php <%s.pcp >%s.c"%(name,names[-1]));

os.system("gcc %s"%" ".join(argv[1:]))

for i in names:
 os.remove("%s.c"%i)
