#!/usr/bin/env python
import os
import sys

argv=sys.argv
names=[]

for idx in range(len(argv)):
 fl=argv[idx]
 if fl[-4:]==".pcp":
  name=fl[:-4]
  names+=[name]
  argv[t]="%s.c"%name
  os.system("php <%s.pcp >%s.c"%(name,name));

os.system("gcc %s"%" ".join(argv[1:]))

for i in names:
 os.system("rm %s.c"%i)
